# Generated by Django 5.1.6 on 2025-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('ARG', 'Argentina'), ('MEX', 'México'), ('COL', 'Colômbia'), ('ES', 'Espanha'), ('FRA', 'França'), ('ITA', 'Itália'), ('GER', 'Alemanha'), ('UK', 'Reino Unido'), ('PR', 'Porto Rico'), ('AU', 'Austrália'), ('ZA', 'África do Sul'), ('NZ', 'Nova Zelândia')], max_length=100, null=True)),
            ],
        ),
    ]
