# Generated by Django 5.1.6 on 2025-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('ARG', 'Argentina'), ('MEX', 'México'), ('COL', 'Colômbia'), ('ES', 'Espanha'), ('FRA', 'França'), ('ITA', 'Itália'), ('GER', 'Alemanha'), ('UK', 'Reino Unido'), ('PR', 'Porto Rico'), ('AU', 'Austrália'), ('ZA', 'África do Sul'), ('NZ', 'Nova Zelândia')], max_length=100, null=True),
        ),
    ]
